spring:
  config:
    activate:
      on-profile: "qa"

loans:
  message: "Welcome to Bank QA APIs "
  contactDetails:
    name: "Jeevith QA"
    email: "jeevith.u.work@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345